#!name=Apple WLOC 加强优化版
#!desc=支持原生Gzip解压。彻底抛弃占位符，直接读取网页存储，无存储则一律透传恢复真实定位。
#!author=rayimj Rewrite (Optimized)
#!homepage=https://github.com/rayimj/wloc
#!icon=https://raw.githubusercontent.com/rayimj/wloc/refs/heads/main/wloc.jpg
#!category=Tools

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://raw.githubusercontent.com/rayimj/wloc/refs/heads/main/dist/wloc.js
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/rayimj/wloc/refs/heads/main/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
